"""sync document version fields

Revision ID: 098e10b5434d
Revises: 1ba28e94c34e
Create Date: 2026-07-15 11:25:07.857354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098e10b5434d'
down_revision: Union[str, Sequence[str], None] = '1ba28e94c34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('storage_path', sa.String(length=1000), nullable=False))
    op.add_column('document_versions', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('document_versions', sa.Column('extraction_status', sa.String(length=30), nullable=False))
    op.add_column('document_versions', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('uploaded_by_id', sa.Integer(), nullable=False))
    op.alter_column('document_versions', 'extracted_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_document_versions_uploaded_by_id'), 'document_versions', ['uploaded_by_id'], unique=False)
    op.create_foreign_key(None, 'document_versions', 'users', ['uploaded_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('document_versions', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_index(op.f('ix_document_versions_uploaded_by_id'), table_name='document_versions')
    op.alter_column('document_versions', 'extracted_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('document_versions', 'uploaded_by_id')
    op.drop_column('document_versions', 'extraction_error')
    op.drop_column('document_versions', 'extraction_status')
    op.drop_column('document_versions', 'mime_type')
    op.drop_column('document_versions', 'storage_path')
    # ### end Alembic commands ###
