"""create employees table

Revision ID: 46ea15b47fe3
Revises: 8aeff8a37356
Create Date: 2026-07-15 21:40:54.561531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ea15b47fe3'
down_revision: Union[str, Sequence[str], None] = '8aeff8a37356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'casual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('12'))
    op.alter_column('employees', 'sick_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('employees', 'annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.drop_constraint(op.f('employees_employee_code_key'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_unique_constraint(op.f('employees_employee_code_key'), 'employees', ['employee_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'annual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('employees', 'sick_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('employees', 'casual_leave_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('12'))
    # ### end Alembic commands ###
