"""create usage analytics tables

Revision ID: b1996e7c2833
Revises: c07821dc16ce
Create Date: 2026-07-15 16:15:14.006165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1996e7c2833'
down_revision: Union[str, Sequence[str], None] = 'c07821dc16ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_endpoint'), 'api_usage_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_method'), 'api_usage_logs', ['method'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_status_code'), 'api_usage_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_user_id'), 'api_usage_logs', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_agent_name'), 'usage_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_usage_logs_conversation_id'), 'usage_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_usage_logs_message_id'), 'usage_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_model_name'), 'usage_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_usage_logs_request_type'), 'usage_logs', ['request_type'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_request_type'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_model_name'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_message_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_conversation_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_agent_name'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_user_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_status_code'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_method'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_endpoint'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
