"""create mcp executions table

Revision ID: c07821dc16ce
Revises: d39ae0a27857
Create Date: 2026-07-15 15:48:16.654173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07821dc16ce'
down_revision: Union[str, Sequence[str], None] = 'd39ae0a27857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_executions_agent_name'), 'mcp_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_mcp_executions_conversation_id'), 'mcp_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_mcp_executions_created_at'), 'mcp_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mcp_executions_id'), 'mcp_executions', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_executions_operation'), 'mcp_executions', ['operation'], unique=False)
    op.create_index(op.f('ix_mcp_executions_success'), 'mcp_executions', ['success'], unique=False)
    op.create_index(op.f('ix_mcp_executions_tool_name'), 'mcp_executions', ['tool_name'], unique=False)
    op.create_index(op.f('ix_mcp_executions_user_id'), 'mcp_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_executions_user_id'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_tool_name'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_success'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_operation'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_id'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_created_at'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_conversation_id'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_agent_name'), table_name='mcp_executions')
    op.drop_table('mcp_executions')
    # ### end Alembic commands ###
