"""extend citation metadata

Revision ID: d39ae0a27857
Revises: a263348f84d4
Create Date: 2026-07-15 14:04:06.657122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39ae0a27857'
down_revision: Union[str, Sequence[str], None] = 'a263348f84d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citations', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('document_version_id', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('chunk_database_id', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('filename', sa.String(length=255), nullable=True))
    op.alter_column('citations', 'chunk_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.alter_column('citations', 'chunk_id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('citations', 'filename')
    op.drop_column('citations', 'version_number')
    op.drop_column('citations', 'chunk_database_id')
    op.drop_column('citations', 'document_version_id')
    op.drop_column('citations', 'document_id')
    # ### end Alembic commands ###
